### ISSUE TITLE
any tutorial?

### ISSUE THREAD

**Issue by Rowing0914** [mikeferguson/moveit_python#18]
frankly, without the tutorial we don't know how to use this....
I am looking forward to seeing the tutorial..

**Comment by gavanderhoorn** [comment]
Have you seen the examples in the [readme](https://github.com/mikeferguson/moveit_python/blob/6fdca782c1918a85eb5f43205eaed26726566cbc/README.md) and the [scripts](https://github.com/mikeferguson/moveit_python/tree/6fdca782c1918a85eb5f43205eaed26726566cbc/scripts) directory? They're pretty self-explanatory (if you know something about MoveIt already).

**Comment by Rowing0914** [comment]
Yes, I have followed them and nothing happend so that I posted.
I ran the script as it is in the README coupled with launching the Fetch Robot in Rviz, but the box didn't appear so I am wondering if there is any complete tutorial which we can literally follow it.

```python
import rospy
from moveit_python import *

rospy.init_node("moveit_py")
# create a planning scene interface, provide name of root link
p = PlanningSceneInterface("base_link")

# add a cube of 0.1m size, at [1, 0, 0.5] in the base_link frame
p.addCube("my_cube", 0.1, 1, 0, 0.5)
```

**Comment by mikeferguson** [comment]
The mobile manipulation demo for Fetch is probably the best documented example that I know of: http://docs.fetchrobotics.com/gazebo.html#mm-demo

That demo shows using Gazebo (to simulate the fetch), MoveIt (to do the actual planning), and a series of scripts using moveit_python to pick stuff up.

It also happens to use navigation to get the robot to the table to do the picking -- I think there was a demo that avoided navigation entirely, but it appears to not be documented anywhere.

**Comment by Rowing0914** [comment]
@mikeferguson 
thank you for sharing it, but unfortunately, I have already covered them all. and I know how to use them but just don't know how to integrate moveit_python to moveit_commander script. and strictly speaking, the demo didn't demostrate how to use `moveit_python`, I think.

**Comment by mikeferguson** [comment]
So moveit_python is completely separate from moveit_commander -- I'd imagine you only need/want to use one at a time (especially since moveit_commander does some weird stuff under the hood with C++ bindings into python).

moveit_python is just a very basic set of pure-python bindings that allow you to streamline the creation and book-keeping for the messages required to send scene updates and planning requests to Moveit. Each of the classes has only a few entry points, the README and example scripts are really the only documentation out there -- other than the code itself.

If you are looking for more extensive documentation, moveit_commander might have some (I really haven't used the commander in a very long time, since I tend to use these simple pure-python bindings).

**Comment by Rowing0914** [comment]
@mikeferguson 
Okay,,, Got it!!
Thank you for your help!
